### PR TITLE
chore(CI): Run hax always, using pre-built docker image

### PR DESCRIPTION
**Pull request by chrysn**
Let's see if building is as fast as I'd expect now that there is a hax image on dockerhub.

### CODE REVIEW

**Comment by geonnave** [comment]
Wow, container pull + hax gen in 2 minutes!

**Comment by chrysn** [comment]
I think this is ready now. Please have an extra look at whether the removal of ead-none is right here. Possibly, we may want to add another line that does the check on the consts module while it is behaving weirdly as you described in chat -- but that's probably nothing that'll stop this PR.

**Comment by chrysn** [comment]
I think this is ready now. Please have an extra look at whether the removal of ead-none is right here. Possibly, we may want to add another line that does the check on the consts module while it is behaving weirdly as you described in chat -- but that's probably nothing that'll stop this PR.

**Comment by geonnave** [comment]
The removal of `ead-none` was right. I pushed a change to reflect the following:
- we are not typechecking the crypto backends
- we want to typecheck edhoc-consts
- call hax with edhoc-consts after edhoc-rs, just in case

**Pull request merged**
